server:
  port: 8081
  context-path: /springboot-day1
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/lpq
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tai
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
    encoding:
      charset: utf-8
mybatis:
  type-aliases-package: com.baizhi.ssm.entity
  mapper-locations: com/baizhi/ssm/*Dao.xml